repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: detect-private-key
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace

-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language_version: python3
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: coverage run -m pytest --cache-clear
        language: system
        pass_filenames: false
        always_run: true
